name: Circadian Tools Build Test
run-name: ${{ github.actor }} is building and testing Circadian Tools 🚀

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ]
    paths-ignore:
      - "README.md"
      - "terraform/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install grcov
      uses: actions-rs/install@v0.1
      with:
        crate: grcov
        version: 0.8.0
        use-tool-cache: true
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
      env:
        RUSTFLAGS: '-Zinstrument-coverage'
        RUSTDOCFLAGS: '-Zinstrument-coverage'
        LLVM_PROFILE_FILE: 'codecov-instrumentation-%p-%m.profraw'
    - name: grcov
      run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch -o lcov.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./lcov.info
